### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by adamskrz** [DevonCrawford/Timelapse-Auto-Ramp-Photoshop-Plugin#11]
Occurs after giving valid filepath (Windows 10 Java(TM) SE Runtime Environment (build 1.8.0_171-b11))

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at proRAW.getPrevImage(proRAW.java:134)
        at proRAW.getImageData(proRAW.java:152)
        at proRAW.retrieveData(proRAW.java:74)
        at proRAW.<init>(proRAW.java:41)
        at proRAW.main(proRAW.java:387)

Have tried different file locations, drives etc.
Will try using java 7 runtime instead

**Comment by adamskrz** [comment]
Using Java 7 it fails to launch at all, saying "Exception in thread "main" java.lang.UnsupportedClassVersionError: proRAW : Unsupported major.minor version 52.0"

**Comment by kenan-kajkus** [comment]
I just made a pull-request on this. It should fix the array issue. But your java7 problem could only be fixed by using java 8
