### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by Bramw2003** [DevonCrawford/Timelapse-Auto-Ramp-Photoshop-Plugin#13]
Please enter the filepath to the first image
in sequence (.CR2 file including extension)

Path: C:\Users\===\Pictures\2018\2018-07-08\_MG_0006.CR2
<b>Exception in thread "main" java.lang.NumberFormatException

: For input string: ":ns:meta/"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at proRAW

.getImageData(proRAW.java:186)
        at proRAW.retrieveData(proRAW.java:74)
        at proRAW.<init>(proRAW.java:41)
        at proRAW.main(proRAW.java:387)
</b>

It seems to be getting this error when it's loading every image into the Image class.
![2018-07-08_2014](https://user-images.githubusercontent.com/17002460/42423552-6a9e608c-82fc-11e8-9843-b91b03eabf3e.png) (It looks like it's getting the error on the first line of the first XMP file it has to load)

**Comment by jdemontigny** [comment]
I'm having this same issue, has anyone been able to solve this? It would be greatly appreciated
