### ISSUE TITLE
Won't run in Terminal on my Mac, prob. wrong version of Java

### ISSUE THREAD

**Issue by lukasbieri** [DevonCrawford/Timelapse-Auto-Ramp-Photoshop-Plugin#14]
Hi Devon,

I really loved your video about coding the timelapse plugin - it is exactly what I always wished for!

Today I wanted to try it for the first time. I shot an amazing timelapse of a sundown in my holidays, but the aperture changes are really distracting. Your plugin should smooth them out in no time :)

Unfortunately, when I try to run the file, I get an error message:

Exception in thread "main" java.lang.UnsupportedClassVersionError: proRAW : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

I'm guessing that I'm running the wrong version of Java, but since I basically know nothing about Java, I was really hoping you could help me solve this issue - thanks a lot in advance!

All the best from Switzerland,
Lukas

**Comment by georgeglessner** [comment]
See #11 , looks like you need to be using Java 8 for this. Just stopped by from YouTube, so not 100% sure.
