### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by jdemontigny** [DevonCrawford/Timelapse-Auto-Ramp-Photoshop-Plugin#16]
been trying to figure this out for a couple days now but this is the error ive been getting after specifying where the path to the first image is.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at proRAW.getPrevImage(proRAW.java:134)
	at proRAW.getImageData(proRAW.java:152)
	at proRAW.retrieveData(proRAW.java:74)
	at proRAW.<init>(proRAW.java:41)
	at proRAW.main(proRAW.java:387)

I'm new to programming so not sure exactly what the error is and how i can fix it

![capture](https://user-images.githubusercontent.com/42181037/43784719-ba349b96-9a32-11e8-9532-0602ead319d3.JPG)

**Comment by popcicle2003** [comment]
I've gotten this too. Did you find a way to fix this? I've tried it on my mac and my windows 10 VM and nothing seems to be working. Will test on an older version of Java to see if that's the issue.

**Comment by erhuz** [comment]
I'm not an expert on photography, but might it be that the image doesn't have a .raw file extension? :thinking:
